services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password        # Root şifresi
      MYSQL_DATABASE: orsettocommerce_db         # Varsayılan bir veritabanı
      MYSQL_USER: my_user                      # Varsayılan kullanıcı
      MYSQL_PASSWORD: my_password              # Kullanıcı şifresi
      MYSQL_ROOT_HOST: '%'                     # Root kullanıcısının tüm IP'lerden erişebilmesi için
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql              # Verilerin kalıcı hale getirilmesi
    command: --default-authentication-plugin=mysql_native_password   # Kimlik doğrulama yöntemini değiştir

volumes:
  mysql_data:
